version: '3.2'


services:
  crawler:
    depends_on:
      - redis-master
    build:
      dockerfile: Dockerfile
      context: ./crawler/
    environment:
      - DB_HOST=redis-master
      - DB_PORT=6379

  app:
    depends_on:
      - redis-master
    build:
      dockerfile: Dockerfile
      context: ./app/
    environment:
      - DB_HOST=redis-master
      - DB_PORT=6379

  nginx:
    depends_on:
      - app
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    ports:
      - 80:80

  redis-master:
    restart: always
    image: redis:latest
    volumes:
      - ./db_data:/data

  redis-slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379